[package]
name = "exploit"
version = "0.1.0"
edition = "2021"
authors = ["[your_name] <[your_email]>"]

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "vault-remediated-2/std"
]
ink-as-dependency = []
e2e-tests = []

[dependencies]
ink = { version = "5.0.0", default-features = false }
vault-remediated-2 = { path = "../", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = "=5.0.0"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
