[package]
name = "delegate-call"
version = "0.1.0"
edition = "2021"
authors = ["[your_name] <[your_email]>"]

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
e2e-tests = []

[dependencies]
ink = { version = "5.0.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
delegate-call-divider = { path = "../divider-example" }
delegate-call-exploiter = { path = "../exploiter-example" }
ink_e2e = "=5.0.0"

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
