name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Login to crates.io
      #   run: echo ${{ secrets.CRATES_TOKEN }} | cargo login

      # - name: Publish to crates.io
      #   run: python scripts/publish-to-crates-io.py

      - name: Create release notes
        run: sed -n "/^## ${{ github.ref_name }}/,/^## v/{ /## v/d; p; }" CHANGELOG.md | awk 'NF {print $0}' | tee body.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: body.md
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-binaries:
    name: Upload binaries
    strategy:
      matrix:
        os:
            - ubuntu-latest
            - macos-latest
            - windows-latest
    runs-on: ${{ matrix.os }}
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          manifest_path: apps/cargo-scout-audit/Cargo.toml
          bin: cargo-scout-audit
          archive: cargo-scout-audit-${{ github.ref_name }}-${{ matrix.os }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
